export const RESET_SEARCH='RESET_SEARCH';
export const SET_EPISODES='SET_EPISODES';
export const SET_CHARACTERS='SET_CHARACTERS';
export const SEARCH_BY_NAME='SEARCH_BY_NAME';
export const SEARCH_BY_EPISODE='SEARCH_BY_EPISODE';